### ISSUE TITLE
bug in integers.downcast_integers line 48

### ISSUE THREAD

**Issue by isaacnfairplay** [isaacnfairplay/polars-types#7]
Traceback (most recent call last):
  File "C:\Users\imoore\OneDrive - Hitachi Group (2)\DataWharehouseSMT\Scripts\Dec2022\Scripts\open_scrap_email.py", line 263, in <module>
    make_report(report_dir, date_scrap, '3A')
  File "C:\Users\imoore\OneDrive - Hitachi Group (2)\DataWharehouseSMT\Scripts\Dec2022\Scripts\open_scrap_email.py", line 116, in make_report
    write(defects, 'defects')
  File "C:\Users\imoore\OneDrive - Hitachi Group (2)\DataWharehouseSMT\Scripts\Dec2022\Scripts\open_scrap_email.py", line 75, in wr
    compress_frame(frame).write_parquet(ppath)
  File "C:\Users\imoore\AppData\Local\Programs\Python\Python311\Lib\site-packages\polarstypes\compress.py", line 7, in compress_frame
    df = downcast_integers(df)
  File "C:\Users\imoore\AppData\Local\Programs\Python\Python311\Lib\site-packages\polarstypes\integers.py", line 49, in downcast_integers
    sorted_types = sorted(compatable_types, key=lambda x: x.bit_resolution)
  File "C:\Users\imoore\AppData\Local\Programs\Python\Python311\Lib\site-packages\polarstypes\integers.py", line 48, in <genexpr>
    compatable_types = (type_range for type_range in TYPE_RANGES if type_range.min_value <= min_value and type_range.max_value >= max_value)
TypeError: '<=' not supported between instances of 'int' and 'NoneType'

**Comment by isaacnfairplay** [comment]
new release 0.1.2 fixes this issue
